### ISSUE TITLE
Add comparison with Telegraf to README

### ISSUE THREAD

**Issue by danielnelson** [mre/kafka-influxdb#48]
As it is possible to use Telegraf with its `kafka_consumer` input to transfer from Kafka to InfluxDB, it would be helpful if Telegraf was added to the comparison section with information about how it compares in terms of performance, feature set, and durability to this project.

I'm the current maintainer of https://github.com/influxdata/telegraf so I'm happy to help with any questions about Telegraf.

**Comment by mre** [comment]
Hi @danielnelson! Thanks for your feedback. Huge fan of telegraf.
Yes, that would for sure be a nice addition. Can you provide some performance data? Preferably I'd love to have a telegraf folder in [here](https://github.com/mre/kafka-influxdb/tree/master/docker). I don't have too much time anymore, so it's tricky from my side to add it to the project. But I would happily accept a pull request for that.

**Comment by danielnelson** [comment]
Yeah, I'll add it in when I get some free time.

**Comment by mre** [comment]
Hey @danielnelson. I assume you're quite busy but I just wanted to follow up on this ticket so that we don't forget. Any updates on the benchmark?

**Comment by danielnelson** [comment]
Sorry, I have only done a little work so far on this but I'd really like to get this going.  I will try to have an update by next week.

**Comment by danielnelson** [comment]
I worked on this today but ran into some issues with the kafka_consumer plugin in Telegraf 1.3 since it still uses the older zookeeper managed offsets.  I was able to get it running with the development branch of Telegraf though, so I think I will wait for version 1.4 to be released before opening a PR, this way I can just use our official docker container.

I did run into quite a few warnings when testing with kafka-influxdb with to the graphite metrics in `docker/kafkacat/messages_graphite.txt` due to the NaN values, is this expected?

Another question, where are you getting the data for the graph in the README from?

**Comment by mre** [comment]
That sounds great! Thanks for that 😃 
Yeah the NaN values are expected. There are quite some invalid metrics in `messages_graphite.txt`. That's on purpose because I wanted to test a more real-world scenario.
The benchmarks from the graph are from a local test setup. There's some more info [here](https://github.com/mre/kafka-influxdb/issues/34#issuecomment-264448606).

**Comment by mre** [comment]
Hey @danielnelson,
sorry for the radio silence. Due to other projects I won't work on kafka-influxdb anymore. That's why I'm closing this for now. In any case, I'd still be curious for a comparison if someone is up to the task. Probably a comparison with [vector](https://vector.dev) might also be fun.
