### ISSUE TITLE
how to mount an external config file and a custom encoder

### ISSUE THREAD

**Issue by mrafeeq** [mre/kafka-influxdb#65]
I have written a custom encoder to convert a json to influxdb format, 

when i use the official image https://hub.docker.com/r/mre0/kafka-influxdb/ 

how to mount an external encoder and a config file as we need to different parameters to the config based on the environment (test/productin)

**Comment by mre** [comment]
Good point! I didn't think of that. 😆 
For a local checkout of the repository, that's easy because you can simply copy the new encoder to the correct folder (kafka_influxdb/encoder) and [use it in the config](https://github.com/mre/kafka-influxdb/blob/master/config_example.yaml#L21).

For Docker, the story is a bit different. Here's how you could do it:

```
docker run -v `pwd`/config.yaml:/usr/src/app/config.yaml -v `pwd`/myencoder.py:/usr/src/app/myencoder.py mre0/kafka-influxdb --encoder=myencoder
```

where `myencoder` is the name of your custom encoder **located in the current directory**. Hope that helps.

**Comment by mre** [comment]
So did this work? @mrafeeq feedback would always be appreciated. 😉

**Comment by mre** [comment]
👍 Thanks for the feedback.
